FROM node:13.12.0-alpine as build

# set working directory
WORKDIR /usr/src/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
#COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts -g --silent

COPY . ./

LABEL js=react

RUN npm run build

# Stage - Production
FROM nginx:1.17-alpine
RUN mkdir /usr/share/nginx/html/react-demo
COPY --from=build /usr/src/app/build /usr/share/nginx/html/react-demo
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]