name: build-docker

on:
  push:
    branches: 
      - dev/digital-ocean-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13.10
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'
    - name: Install npm
      run: |
        npm install
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: shershen08/react-demo-deploy-app/my-app
        registry: docker.pkg.github.com
        username: ${{ secrets.USERNAME_FULL }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile-prod
        tags: latest
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.USERNAME_FULL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: USERNAME_FULL, GITHUB_TOKEN
        script: |
          docker stop $(docker ps -a -q)
          docker login docker.pkg.github.com -u $USERNAME_FULL -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/shershen08/react-demo-deploy-app/my-app:latest
          docker run -dit -p 80:80 docker.pkg.github.com/shershen08/react-demo-deploy-app/my-app:latest